driver:
  name: vagrant

provisioner:
  name: chef_zero
platforms:

- name: ubuntu-14.04
  run_list:
    - recipe[packagecloud_test::distro_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems]

- name: ubuntu-16.04
  run_list:
    - recipe[packagecloud_test::distro_deps]
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems_private]

- name: centos-6.8
  run_list:
    - recipe[packagecloud_test::distro_deps]
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: centos-7.3
  run_list:
    - recipe[packagecloud_test::distro_deps]
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems_private]

- name: amazon-linux
  driver_config:
    box: mvbcoding/awslinux
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

suites:
- name: default
  run_list:
